#!/usr/bin/env bash
# ==============================================================================
# op-write-ssh-key.sh — write the Ansible SSH keypair into 1Password via the
# DESKTOP `op` CLI (account mode), Connect-INDEPENDENT. Invoked by the
# null_resource.ansible_ssh_key_writeback local-exec in ../ssh-keys.tf.
#
# WHY: opconnect is the secrets ROOT — it provisions the VM that runs 1Password
# Connect, so it cannot use the onepassword Terraform provider (that needs
# Connect or an SA token, neither available pre-bootstrap). The desktop op CLI
# authenticates in ACCOUNT mode without Connect, so it can seed the item that
# Connect (once up) then serves to tofu/compute + the ansible ssh-key-loader.
#
# SECRET HYGIENE: the private key arrives via ENV (never argv — avoids the
# ps/argv leak the classifier correctly blocks) and is written only into a 0600
# mktemp template consumed by `op item create --template`, then shredded.
# Connect/SA env vars are stripped to force account mode. Idempotent: no-op when
# the stored fingerprint already matches the generated key.
# ==============================================================================
set -euo pipefail

: "${OP_VAULT:?OP_VAULT required}"
: "${OP_ITEM_TITLE:?OP_ITEM_TITLE required}"
: "${SSH_PUBLIC_KEY:?SSH_PUBLIC_KEY required}"
: "${SSH_PRIVATE_KEY:?SSH_PRIVATE_KEY required}"
: "${KEY_TYPE:?KEY_TYPE required}"
: "${SSH_PUBLIC_KEY_FP:?SSH_PUBLIC_KEY_FP required}"
OP_NOTE="${OP_NOTE:-Ansible SSH keypair generated by OpenTofu (tofu/opconnect/ssh-keys.tf).}"

# Force desktop/account mode (NOT Connect, NOT SA token). `command env` ensures
# the external env(1) runs the external op(1) — the op arg is a program for env
# to exec, never this wrapper, so there is no recursion.
op() { command env -u OP_CONNECT_HOST -u OP_CONNECT_TOKEN -u OP_SERVICE_ACCOUNT_TOKEN op "$@"; }

# Read one field's value by label from the item JSON (robust to section nesting).
get_field() {
  op item get "$OP_ITEM_TITLE" --vault "$OP_VAULT" --format json 2>/dev/null \
    | python3 -c "import sys,json
try: d=json.load(sys.stdin)
except Exception: sys.exit(0)
print(next((f.get('value','') for f in d.get('fields',[]) if f.get('label')=='$1'), ''))" 2>/dev/null || true
}

# Idempotency: if the stored fingerprint matches, nothing to do.
existing_fp="$(get_field public_key_fingerprint_sha256)"
if [ -n "$existing_fp" ] && [ "$existing_fp" = "$SSH_PUBLIC_KEY_FP" ]; then
  echo "op-write-ssh-key: '$OP_ITEM_TITLE' already current (fingerprint match) — no-op."
  exit 0
fi

# Present but stale/incomplete -> replace cleanly (title-stable; readers key on title).
if op item get "$OP_ITEM_TITLE" --vault "$OP_VAULT" >/dev/null 2>&1; then
  echo "op-write-ssh-key: '$OP_ITEM_TITLE' present but stale — replacing."
  op item delete "$OP_ITEM_TITLE" --vault "$OP_VAULT"
fi

# Build the item template; the private key lives ONLY in this 0600 file.
tmpl="$(mktemp)"
chmod 600 "$tmpl"
cleanup() { command shred -u "$tmpl" 2>/dev/null || rm -f "$tmpl"; }
trap cleanup EXIT

python3 - >"$tmpl" <<'PY'
import json, os
print(json.dumps({
    "title": os.environ["OP_ITEM_TITLE"],
    "category": "SECURE_NOTE",
    "tags": ["opentofu", "ansible", "ssh", "infrastructure"],
    "sections": [{"label": "Private Key"}, {"label": "Public Key"}],
    "fields": [
        {"type": "STRING", "purpose": "NOTES", "label": "notesPlain", "value": os.environ["OP_NOTE"]},
        {"section": {"label": "Private Key"}, "type": "CONCEALED", "label": "private_key", "value": os.environ["SSH_PRIVATE_KEY"]},
        {"section": {"label": "Private Key"}, "type": "STRING", "label": "key_type", "value": os.environ["KEY_TYPE"]},
        {"section": {"label": "Public Key"}, "type": "STRING", "label": "public_key", "value": os.environ["SSH_PUBLIC_KEY"]},
        {"section": {"label": "Public Key"}, "type": "STRING", "label": "public_key_fingerprint_sha256", "value": os.environ["SSH_PUBLIC_KEY_FP"]},
    ],
}))
PY

op item create --vault "$OP_VAULT" --template "$tmpl" >/dev/null
echo "op-write-ssh-key: created '$OP_ITEM_TITLE' in vault $OP_VAULT."

# Verify the readers' fields resolve before declaring success.
got_pub="$(get_field public_key)"
got_priv_present="$(op item get "$OP_ITEM_TITLE" --vault "$OP_VAULT" --fields label=private_key >/dev/null 2>&1 && echo yes || echo no)"
if [ -z "$got_pub" ] || [ "$got_priv_present" != "yes" ]; then
  echo "op-write-ssh-key: VERIFY FAILED (public_key empty or private_key missing)" >&2
  exit 1
fi
echo "op-write-ssh-key: verified public_key + private_key fields resolve."
