# ==============================================================================
# PostgreSQL LXC Container Infrastructure
# ==============================================================================
# This file defines a SINGLE LXC container for PostgreSQL database server
# This container will host MULTIPLE databases (wazuh, etc.)
# Configuration and PostgreSQL installation is handled by Ansible
#
# Uses standard Debian 12 LXC template from Proxmox. Ansible prerequisites
# (python3, sudo) are installed via bootstrap playbook using raw module.
# ==============================================================================

# Create single PostgreSQL LXC container
# This container will host multiple databases for different services
resource "proxmox_virtual_environment_container" "postgresql" {
  node_name = "pve"
  vm_id     = var.postgresql_lxc_config.vm_id

  # Container basic settings
  description   = var.postgresql_lxc_config.description
  started       = var.postgresql_lxc_config.started
  start_on_boot = var.postgresql_lxc_config.on_boot
  unprivileged  = true # Security best practice - always use unprivileged containers

  # Operating System - Standard Debian 12 template from Proxmox
  # Ansible prerequisites installed via bootstrap playbook
  operating_system {
    template_file_id = proxmox_virtual_environment_download_file.debian12_lxc_template.id
    type             = "debian"
  }

  # CPU Configuration
  cpu {
    cores = var.postgresql_lxc_config.cpu_cores
  }

  # Memory Configuration
  memory {
    dedicated = var.postgresql_lxc_config.memory_mb
    swap      = 512 # Small swap for safety
  }

  # Root Disk Configuration
  disk {
    datastore_id = "vm-data"
    size         = var.postgresql_lxc_config.disk_gb
  }

  # Network Configuration - DHCP on vmbr0
  network_interface {
    name   = "eth0"
    bridge = "vmbr0"
    # DHCP - IP will be retrieved via output after creation
  }

  # Console Settings
  console {
    enabled   = true
    type      = "console"
    tty_count = 2
  }

  # Initialization - SSH key generated by Terraform and stored in 1Password
  initialization {
    hostname = var.postgresql_lxc_config.hostname

    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }

    user_account {
      keys = [
        # Terraform-generated SSH key for Ansible access
        # Private key stored in 1Password: "Infrastructure Ansible SSH Key"
        trimspace(tls_private_key.ansible.public_key_openssh)
      ]
    }
  }

  # Features
  features {
    nesting = true # Allow Docker/nested containers if needed
  }

  # Tags for organization
  tags = var.postgresql_lxc_config.tags
}

# ==============================================================================
# 1Password Integration - PostgreSQL Database Credentials
# ==============================================================================
# These resources create 1Password items for database credentials
# Ansible will retrieve these secrets during configuration
# ==============================================================================

# PostgreSQL Admin (postgres) password item in 1Password
resource "onepassword_item" "postgresql_admin" {
  vault    = var.onepassword_vault_id
  category = "database"
  title    = "PostgreSQL Admin (postgres)"
  tags     = ["terraform", "postgresql", "homelab", "admin"]

  type     = "postgresql"
  hostname = "${var.postgresql_lxc_config.hostname}.fusioncloudx.home"
  port     = "5432"
  database = "postgres"
  username = "postgres"

  password_recipe {
    length  = 32
    symbols = true
  }
}

# Wazuh database user password item in 1Password
resource "onepassword_item" "wazuh_db_user" {
  vault    = var.onepassword_vault_id
  category = "database"
  title    = "PostgreSQL - Wazuh Database User"
  tags     = ["terraform", "postgresql", "wazuh", "homelab"]

  type     = "postgresql"
  hostname = "${var.postgresql_lxc_config.hostname}.fusioncloudx.home"
  port     = "5432"
  database = "wazuh"
  username = "wazuh"

  password_recipe {
    length  = 32
    symbols = true
  }
}
