# ==============================================================================
# 1Password Items - FusionCloudX Infrastructure
# ==============================================================================
# All 1Password credential items managed by Terraform, organized by service.
# Ansible references these by item *title* (not resource name).
# ==============================================================================

# ------------------------------------------------------------------------------
# SSH Key
# ------------------------------------------------------------------------------

resource "onepassword_item" "ansible_ssh_key" {
  vault    = var.onepassword_vault_id
  category = "secure_note"
  title    = "Infrastructure Ansible SSH Key"
  tags     = ["terraform", "ansible", "ssh", "infrastructure"]

  note_value = <<-EOT
    SSH key pair generated by Terraform for Ansible access to infrastructure.

    Usage:
    - Public key is automatically deployed to VMs/containers via cloud-init
    - Private key can be extracted with: op read "op://FusionCloudX/Infrastructure Ansible SSH Key/Private Key/private_key"
    - Or manually copy to ~/.ssh/ansible_ed25519

    Generated: ${timestamp()}
  EOT

  section {
    label = "Private Key"

    field {
      label = "private_key"
      type  = "CONCEALED"
      value = tls_private_key.ansible.private_key_openssh
    }

    field {
      label = "key_type"
      type  = "STRING"
      value = "ED25519"
    }
  }

  section {
    label = "Public Key"

    field {
      label = "public_key"
      type  = "STRING"
      value = tls_private_key.ansible.public_key_openssh
    }

    field {
      label = "public_key_fingerprint_sha256"
      type  = "STRING"
      value = tls_private_key.ansible.public_key_fingerprint_sha256
    }
  }

  # Ignore timestamp changes in note_value
  lifecycle {
    ignore_changes = [note_value]
  }
}

# ------------------------------------------------------------------------------
# PostgreSQL Credentials
# ------------------------------------------------------------------------------

# PostgreSQL Admin (postgres) password
resource "onepassword_item" "postgresql_admin" {
  vault    = var.onepassword_vault_id
  category = "database"
  title    = "PostgreSQL Admin (postgres)"
  tags     = ["terraform", "postgresql", "homelab", "admin"]

  type     = "postgresql"
  hostname = "${var.postgresql_lxc_config.hostname}.fusioncloudx.home"
  port     = "5432"
  database = "postgres"
  username = "postgres"

  password_recipe {
    length  = 32
    symbols = true
  }
}

# Wazuh database user password
resource "onepassword_item" "wazuh_db_user" {
  vault    = var.onepassword_vault_id
  category = "database"
  title    = "PostgreSQL - Wazuh Database User"
  tags     = ["terraform", "postgresql", "wazuh", "homelab"]

  type     = "postgresql"
  hostname = "${var.postgresql_lxc_config.hostname}.fusioncloudx.home"
  port     = "5432"
  database = "wazuh"
  username = "wazuh"

  password_recipe {
    length  = 32
    symbols = true
  }
}

# Mealie database user password
resource "onepassword_item" "mealie_db_user" {
  vault    = var.onepassword_vault_id
  category = "database"
  title    = "PostgreSQL - Mealie Database User"
  tags     = ["terraform", "postgresql", "mealie", "homelab"]

  type     = "postgresql"
  hostname = "${var.postgresql_lxc_config.hostname}.fusioncloudx.home"
  port     = "5432"
  database = "mealie"
  username = "mealie"

  password_recipe {
    length  = 32
    symbols = true
  }
}

# Tandoor database user password
resource "onepassword_item" "tandoor_db_user" {
  vault    = var.onepassword_vault_id
  category = "database"
  title    = "PostgreSQL - Tandoor Database User"
  tags     = ["terraform", "postgresql", "tandoor", "homelab"]

  type     = "postgresql"
  hostname = "${var.postgresql_lxc_config.hostname}.fusioncloudx.home"
  port     = "5432"
  database = "tandoor"
  username = "tandoor"

  password_recipe {
    length  = 32
    symbols = true
  }
}

# ------------------------------------------------------------------------------
# GitLab Credentials
# ------------------------------------------------------------------------------

# GitLab root user password
resource "onepassword_item" "gitlab_root_password" {
  vault    = var.onepassword_vault_id
  category = "login"
  title    = "GitLab Root User"
  tags     = ["terraform", "gitlab", "homelab"]

  username = "root"
  password_recipe {
    length  = 32
    symbols = true
  }
}

# GitLab runner registration token (for future CI/CD use)
resource "onepassword_item" "gitlab_runner_token" {
  vault    = var.onepassword_vault_id
  category = "password"
  title    = "GitLab Runner Registration Token"
  tags     = ["terraform", "gitlab", "homelab"]

  password_recipe {
    length  = 32
    symbols = false # Alphanumeric only for tokens
  }
}

# ------------------------------------------------------------------------------
# Tandoor Application Secrets
# ------------------------------------------------------------------------------

resource "onepassword_item" "tandoor_secret_key" {
  vault    = var.onepassword_vault_id
  category = "password"
  title    = "Tandoor Secret Key"
  tags     = ["terraform", "tandoor", "homelab"]

  password_recipe {
    length  = 50
    symbols = false # Django SECRET_KEY typically alphanumeric
  }
}
