# ==============================================================================
# Infrastructure SSH Key Generation
# ==============================================================================
# Generates SSH key pair for Ansible to access VMs and containers.
# The key is stored in 1Password via onepassword.tf.
#
# Key Architecture:
# - Bootstrap/Terraform Key: Pre-existing in 1Password SSH agent
#   Used by: bpg/proxmox provider SSH, terraform@pve access
#   Setup: Manual (GitHub keys already in 1Password SSH agent)
#
# - Infrastructure-Ansible Key (this file): Generated by Terraform
#   Used by: Ansible to SSH into provisioned VMs/containers
#   Setup: Automatic (created via 1Password Terraform provider)
# ==============================================================================

# Generate ED25519 SSH key pair for Ansible
resource "tls_private_key" "ansible" {
  algorithm = "ED25519"
}
