# ==============================================================================
# Infrastructure SSH Key Management
# ==============================================================================
# Generates SSH key pair for Ansible to access VMs and containers
# Private key stored in 1Password as secure_note with custom fields
#
# Key Architecture:
# - Bootstrap/Terraform Key: Pre-existing in 1Password SSH agent
#   Used by: bpg/proxmox provider SSH, terraform@pve access
#   Setup: Manual (GitHub keys already in 1Password SSH agent)
#
# - Infrastructure-Ansible Key (this file): Generated by Terraform
#   Used by: Ansible to SSH into provisioned VMs/containers
#   Setup: Automatic (created via 1Password Terraform provider)
#
# Note: The 1Password Terraform provider doesn't support SSH_KEY category,
# so we store the key as a secure_note. To use with SSH agent, manually
# copy the private key to ~/.ssh/ or use `op read` to extract it.
# ==============================================================================

# Generate ED25519 SSH key pair for Ansible
resource "tls_private_key" "ansible" {
  algorithm = "ED25519"
}

# ==============================================================================
# Create SSH Key in 1Password as Secure Note
# ==============================================================================
# The 1Password Terraform provider only supports login/password/database/secure_note
# categories. We use secure_note to store both private and public keys with
# custom sections for organization.
# ==============================================================================

resource "onepassword_item" "ansible_ssh_key" {
  vault    = var.onepassword_vault_id
  category = "secure_note"
  title    = "Infrastructure Ansible SSH Key"
  tags     = ["terraform", "ansible", "ssh", "infrastructure"]

  note_value = <<-EOT
    SSH key pair generated by Terraform for Ansible access to infrastructure.

    Usage:
    - Public key is automatically deployed to VMs/containers via cloud-init
    - Private key can be extracted with: op read "op://FusionCloudX/Infrastructure Ansible SSH Key/Private Key/private_key"
    - Or manually copy to ~/.ssh/ansible_ed25519

    Generated: ${timestamp()}
  EOT

  section {
    label = "Private Key"

    field {
      label = "private_key"
      type  = "CONCEALED"
      value = tls_private_key.ansible.private_key_openssh
    }

    field {
      label = "key_type"
      type  = "STRING"
      value = "ED25519"
    }
  }

  section {
    label = "Public Key"

    field {
      label = "public_key"
      type  = "STRING"
      value = tls_private_key.ansible.public_key_openssh
    }

    field {
      label = "public_key_fingerprint_sha256"
      type  = "STRING"
      value = tls_private_key.ansible.public_key_fingerprint_sha256
    }
  }

  # Ignore timestamp changes in note_value
  lifecycle {
    ignore_changes = [note_value]
  }
}
