# ==============================================================================
# Ansible SSH key — GENERATED here; written to 1Password via the DESKTOP op CLI
# (Connect-INDEPENDENT), NOT via the onepassword Terraform provider.
# ==============================================================================
# opconnect is the secrets ROOT: it provisions the VM that runs 1Password
# Connect, so it must apply WITHOUT depending on Connect (and no SA token
# exists). The onepassword TF provider authenticates ONLY via Connect or an SA
# token — so owning the key as an `onepassword_item` RESOURCE forced a live-
# Connect dependency on every opconnect apply. That was the regression this file
# now fixes (option D, minimal blast radius).
#
# FIX: generate the keypair here, use the public half for the opconnect VM's own
# cloud-init, and WRITE both halves to the "Infrastructure Ansible SSH Key"
# 1Password secure_note via the desktop `op` CLI in ACCOUNT mode — which works
# WITHOUT Connect (the same out-of-band trust path that seeds Connect's OWN
# credentials). No onepassword provider in this state's graph → opconnect
# applies Connect-free. tofu/compute (its Connect data source) and the ansible
# ssh-key-loader role READ the item UNCHANGED; Connect, once up, serves it.
#
# Durable best-practice options (AWS SSM anchor / IAM Roles Anywhere / ephemeral
# write-only #8) are deferred — see docs/enhance-harden-later.md + task #68.
#
# Private-key-in-state: tls_private_key keeps the private key in this state,
# which is S3 + SSE-KMS + enforced OpenTofu aes_gcm — the same posture as the DB
# passwords in tofu/compute/secrets.tf (#8 ephemeral/write-only deferred).
# ==============================================================================

resource "tls_private_key" "ansible" {
  algorithm = "ED25519"
}

# Write-back to 1Password via the desktop op CLI (Connect-independent). The
# private key is passed by ENV (never argv) into scripts/op-write-ssh-key.sh,
# which builds a 0600 template and `op item create`s it, then shreds it. STATIC
# trigger keyed on the public-key fingerprint (NO timestamp() — footgun #8) so
# the key is stable and re-applies are no-ops; the script itself also no-ops
# when the stored fingerprint already matches.
resource "null_resource" "ansible_ssh_key_writeback" {
  triggers = {
    fingerprint = tls_private_key.ansible.public_key_fingerprint_sha256
    item_title  = var.ansible_ssh_key_item_title
    vault       = var.onepassword_vault_id
  }

  provisioner "local-exec" {
    # Run via `bash` explicitly so the script executes regardless of the
    # committed file mode (a fresh clone gets 100644 -> bare-path exec would be
    # "Permission denied"). The path is quoted because the repo path contains a
    # space ("FusionCloudX Infrastructure"). The file is ALSO committed +x.
    command = "bash '${abspath("${path.module}/scripts/op-write-ssh-key.sh")}'"
    environment = {
      OP_VAULT          = var.onepassword_vault_id
      OP_ITEM_TITLE     = var.ansible_ssh_key_item_title
      SSH_PUBLIC_KEY    = tls_private_key.ansible.public_key_openssh
      SSH_PRIVATE_KEY   = tls_private_key.ansible.private_key_openssh
      KEY_TYPE          = "ED25519"
      SSH_PUBLIC_KEY_FP = tls_private_key.ansible.public_key_fingerprint_sha256
      OP_NOTE           = "Ansible SSH keypair generated by OpenTofu (tofu/opconnect/ssh-keys.tf) and written to 1Password via the desktop op CLI (Connect-independent). Public key auto-deployed via cloud-init; private key read by the ansible ssh-key-loader role. Do not edit by hand."
    }
  }
}

locals {
  # opconnect generates the key, so use the generated public key directly for
  # the opconnect VM's own cloud-init (no 1Password read — Connect-independent).
  ansible_ssh_public_key = trimspace(tls_private_key.ansible.public_key_openssh)
}
